version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  graphql:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

volumes:
  mongodb-data:
